### ISSUE TITLE
I would like to ask for help

### ISSUE THREAD

**Issue by fireedwin** [lllyasviel/Paints-UNDO#104]
[spyder](paints_undo) C:\Users\edwin.MILKTEA\Paints-UNDO>python gradio_app.py
Traceback (most recent call last):
  File "C:\Users\edwin.MILKTEA\Paints-UNDO\gradio_app.py", line 15, in <module>
    import memory_management
  File "C:\Users\edwin.MILKTEA\Paints-UNDO\memory_management.py", line 9, in <module>
    torch.zeros((1, 1)).to(gpu, torch.float32)
  File "C:\Users\edwin.MILKTEA\AppData\Local\spyder-6\envs\paints_undo\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I try to fix it but it keep having the same problem

**Comment by fireedwin** [comment]
nvm I found the problem
make sure your setup enviorment should be:
torch 2.5.1+cu121
torchaudio 2.5.1+cu121
torchvision               0.20.1+cu121
xformers 0.0.25.post1
and don't forget about install huggingface-hub (my version is Version: 0.25.1) and diffusers (my version: 0.28.0)
also remember the step of pip install -r requirements.txt
lol
